language: java

notifications:
  webhooks: https://outlook.office.com/webhook/5bf4d308-5cf2-465a-a4e4-09d30d758129@f2d7d6c5-1bee-41ff-9e79-b372a5cce71d/TravisCI/91624a1f9c49487ca121ad4fe8a66c86/2a34827c-52af-49e6-b943-61ebcd58510e
  on_success: change # default: always
  on_failure: always # default: always
  on_start: change   # default: never
  on_cancel: always # default: always
  on_error: always # default: always

addons:
  sonarcloud:
    organization: "knowagelabs"
    token: ${SONAR_TOKEN}

jdk:
  - openjdk8

script:
  - travis_wait 30 mvn -q -f knowage-ce-parent/pom.xml clean compile

after_success:
  - mvn -f jdbccore/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowage-core/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowage-e2e-testing/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowage/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagebirtreportengine/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagecockpitengine/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagecommonjengine/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagedao/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagedataminingengine/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagegeoreportengine/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagejasperreportengine/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagekpiengine/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowageldapsecurityprovider/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagemeta/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagenetworkengine/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowageoauth2securityprovider/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowageqbeengine/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagesdk/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagesvgviewerengine/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagetalendenginclientapi/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagetalendengine/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagetest/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowageutils/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowageutilsjson/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f knowagewhatifengine/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f qbecore/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f slimerjs-wrapper/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f spagobi-commons-core/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f spagobi-cwm/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f spagobi-metamodel-core/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f spagobi-metamodel-utils/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**
  - mvn -f spagobi.birt.oda/pom.xml sonar:sonar -Dsonar.exclusions=src/main/webapp/js/lib/**,src/main/webapp/js/extjs/**,src/main/webapp/node_modules/**

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
